language: python
python:
- '3.5'
before_script: mkdir -p dist
script: ./index-addons.py --out-dir dist xbmc.beardypig.plugins
deploy:
  provider: s3
  skip_cleanup: true
  local_dir: dist/
  access_key_id: AKIAJA536STKTMHCZFZQ
  secret_access_key:
    secure: HlZcjf0NPmNT0KYTjllhwbO0QZAl5XE77uI6ZRcylg8NIzbx0aKY1oGSI/hw0Iavp5HMY4fxSLU9NFs9n1h4r/5bJdWroOIfHEbasoXdiqyZgQBT+F/rNpy3E2jQFAzP8XTz9IN3SWtwZMImHKVoK1SUoH8Q1TAFaCuGshCQOqYTsxzJktqNYvDUwcJB7UnxuGjzTxtjXUOMt/yAxbQMuDYohRx+HSVI3BeBSwlCG/nSn/1GwsjBje1yZTdx5sNI8DxNM4+z/EawuJdw3QruQM+UhpYwNfZAtbULxrk9F9twSn+43J8mp9KvNFCNxvWeGz05C4zpsBotgJNsYSRkJrixP9PiinUtgn4AuB0Vtj69+gSH4TrslFtDYyxt0p4Ygd903OknssIHT7qpV/Vc40bgzbsFyIbiI2GlGs3mAED1zDPTWlDG6TI4TDeq8hZGZnaYDMrnyoRhnF33kA7or6jz/T70ifTDJc/jgCM+2Fdmnh6Av79FQ4dCYvt6NLQ9cEe3JEOhzu94Mdxb+smsE/wGr2zmRzbLC/B3Hd0FP9rCaC4cCteLvzpRm3NKFWSultrqtw8wwwLSbWS4sWDydDurlZ/NF/7erW111WFntwOCnpBCrRA8IOb8ASMTv665HlpoyskoBoSFe13MliALNv1n35iSk+b14y9jA4OTkUc=
  bucket: xbmc.beardypig.plugins
  on:
    repo: beardypig/xbmc.beardypig.plugins
