language: python
python:
- '3.5'
script: python addons.py addons/*
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key.pem
- ssh-add .travis/deploy_key.pem
- touch index.html
- git checkout -b gh-pages-staging
- git config --global user.email "build@travis-ci.org"
- git config --global user.name "Travis CI"
- git add -f addons.xml addons.xml.md5 index.html
- git commit -m "updated addons.xml and addons.xml.md5"
- git remote add deploy git@github.com:beardypig/xbmc.beardypig.plugins.git
- git push -f deploy gh-pages-staging:gh-pages
before_install:
- openssl aes-256-cbc -K $encrypted_aef3a89f5763_key -iv $encrypted_aef3a89f5763_iv
  -in deploy_key.pem.enc -out .travis/deploy_key.pem -d
